### ISSUE TITLE
Need immediate chaos

### ISSUE THREAD

**Issue by i0natan** [asobti/kube-monkey#47] opened 2018-03-19 13:11 UTC
It could have been nice, if this tool can perform quick chaos over a short and immediate priod of time. Our team wants to test the app resiliency in 20min/1 hour, not to wait the whole weak long before drawing conclusions.

**Comment by asobti** [comment] 2018-03-20 01:03
@i0natan You can configure the time window when kube-monkey kills pods. Say, you configure kube-monkey to build a schedule at 10am and kill pods between 10.05am and 10.30am. Would that work?

**Comment by i0natan** [comment] 2018-03-20 07:50
that will work but couldn't find within the docs exact timing for killing pods, can you kindly refer to it?

**Comment by camilocot** [comment] 2018-04-12 11:29
@i0natan the schedule settings are detailed in the [configuring](https://github.com/asobti/kube-monkey#configuring) section

**Comment by yao-xu** [comment] 2018-06-04 22:48
@camilocot @i0natan Can you kindly clarify a little more? Can `run_hour`, `start_hour` and `end_hour` be float or format like 08:10? I tried to edit the configuration file or config map to get immediate chaos. I tried `run_hour=8.10` and `run_hour=8:10`. With the former one, kube-monkey still runs at 8am instead of 8:10am; with the latter one, it just crashed. 
Thanks

**Comment by pawarmanoj** [comment] 2018-07-03 18:19
As a workaround, configuring debug mode in the config.toml will schedule the execution of kube-monkey runs every 'schedule_delay' seconds. For execution every 30 seconds, i configure it as below. 
`[debug]
enabled = true
schedule_delay=30
force_should_kill = true
schedule_immediate_kill = true`

**Comment by pawarmanoj** [comment] 2018-07-03 18:19
[debug]
enabled = true
schedule_delay=30
force_should_kill = true
schedule_immediate_kill = true

**Comment by Spellchaser** [comment] 2018-07-04 08:43
This is as intended for immediate chaos. If it's unclear in the docs, a PR
is welcome.

**Comment by asobti** [comment] 2018-07-09 22:55
> I think having a feature to schedule/kill on more than just days is a good feature
@Spellchaser can you elaborate what you mean by this? Do you mean the ability to, for example, specify a pod to be killed every 'n' hours?

**Comment by asobti** [comment] 2018-11-27 03:30
Closing this issue. Open to more specific feature requests to be filed as follow up issues

**Closed by asobti** 2018-11-27 03:30 UTC
Labels: enhancement
